# -*- coding: utf-8 -*-

{
    'name': 'Affinity Gate Pass',
    'author': 'Affinity Business Suite',
    'website': 'https://affinitysuite.net',
    'support': 'info@affinitysuite.net',
    'category': 'Accounting',
    'summary': 'Affinity Gate Pass Module',
    'description': '''Affinity Gate Pass Module''',
    'version': '18.0',
    'depends': ['sale_stock', 'purchase'],
    'data': [
        'data/ir_sequence.xml',
        'data/report_paperformat.xml',
        'security/ir.model.access.csv',
        'security/ir_rule.xml',
        'report/report_gate_in_template.xml',
        'report/report_gate_out_template.xml',
        'report/report_gate_pass_guest.xml',
        'report/ir_actions_report.xml',
        'views/gate_pass_guest_views.xml',
        'views/gate_pass_in_views.xml',
        'views/gate_pass_out_views.xml',
        'views/purchase_order_views.xml',
        'views/sale_order_views.xml',
        'views/stock_picking_views.xml',
    ],
    'assets': {
        'web.assets_backend': [
            'affinity_gate_pass/static/src/components/product_line_description/product_line_description.js',
            'affinity_gate_pass/static/src/components/product_line_description/product_line_description.xml',
        ],
    },
    'price': 4000000,
    'currency': 'EUR',
    'license': 'OPL-1',
    'application': False,
    'auto_install': False,
    'installable': True,
}
